### PR TITLE
Auto package update: Theme last update day file

### PR DESCRIPTION
**Pull request by YourFin**
Theme `apu--last-update-day-path'.
This file is used to store raw text and is the only data file of the package.

[Auto Package Update repo](https://github.com/rranelli/auto-package-update.el)

### CODE REVIEW

**Comment by tarsius** [comment]
Let's wait for https://github.com/rranelli/auto-package-update.el/issues/31.

**Comment by YourFin** [comment]
Alright, I wasn't entirely sure how to handle this; thanks for the work you're doing!

**Comment by YourFin** [comment]
Sorry hit close and comment by accident

**Comment by tarsius** [comment]
I am closing this -- on purpose ;-)

To be honest, I do so mostly to have a clear slate -- this is the only open pull request in any of my repositories, except Magit of course. :wink: 

Please open a new pr once upstream has fixed the mentioned issue.

**Comment by YourFin** [comment]
Ok, I'll try and put in a pull request upstream at some point this week, as this is going to bother me. Hopefully this will get finished.

Thanks for the work you do, and congrats on the kickstarter getting funded. Can't wait to get another sticker to plaster on the back of my laptop!

**Comment by YourFin** [comment]
[Pull request](https://github.com/rranelli/auto-package-update.el/pull/32)

**Pull request closed without merging**
