### PR TITLE
dired-recent: theme dired-recent-directories-file

### PR DESCRIPTION
**Pull request by manuel-uberti**
[dired-recent](https://github.com/vifon/dired-recent.el) keeps a history of paths visited with Dired.

`dired-recent-directories-file` contains the above mentioned paths.

### CODE REVIEW

**Comment by tarsius** [comment]
What's the format used in the file? If it's a s-expression, then the file should have an `.el` suffix.

**Comment by manuel-uberti** [comment]
It's a list of strings. Let me ping @Vifon on this.

**Comment by Vifon** [comment]
Yes, it's a s-expression. Should I change the suffix upstream too?

**Comment by tarsius** [comment]
> Yes, it's a s-expression. Should I change the suffix upstream too?

It's only a `no-littering`-convention to do so and I would recommend against changing the default unless you also put some mechanism in place to rename an existing file.

**Comment by manuel-uberti** [comment]
Is there something I can do to help, then?

**Comment by tarsius** [comment]
Yes, update this pr to append the `.el`.

**Comment by manuel-uberti** [comment]
Done :)

**Comment by manuel-uberti** [comment]
Any chance for this?

**Comment by manuel-uberti** [comment]
Another friendly ping :)

**Comment by tarsius** [comment]
Sorry I forgot about this -- I blame it on the kid. Most have gotten interrupted after checking out the pr but before responding. Anyway...

As per the conventions this file should be named "dired-recent-directories.el".

**Comment by manuel-uberti** [comment]
You're right, of course. Done! :)

**Comment by tarsius** [comment]
I have applied this. Thanks!

Please use a dedicated feature branch next time. See https://github.com/magit/magit/wiki/Dedicated-pull-request-branches.

**Comment by manuel-uberti** [comment]
Sure thing. Thank you.

**Pull request closed without merging**
