### PR TITLE
omnisharp: theme omnisharp-cache-directory

### PR DESCRIPTION
**Pull request by DamienCassou**
I think I followed all conventions. Please tell me if I didn't. The only thing I'm not sure about is if the subdirectory "cache/" is necessary or if "omnisharp/" would have been enough. There is no other variable to theme.

> please link to the repository of the package that your pull request is theming.

- https://github.com/OmniSharp/omnisharp-emacs

### CODE REVIEW

**Comment by tarsius** [comment]
I cannot find that symbol anywhere in that package - not even using `rgrep` or `git log -G omnisharp-cache-directory`. I sense there must be a typo or something, but I don't see it :wink:

**Comment by DamienCassou** [comment]
It works for me: https://github.com/OmniSharp/omnisharp-emacs/search?utf8=%E2%9C%93&q=omnisharp-cache-directory&type=.

**Comment by tarsius** [comment]
Ah! Didn't update the Emacsmirror (or more specifically my local copy) in the last ~~24~~ 23 hours. :stuck_out_tongue_closed_eyes:

**Comment by tarsius** [comment]
> The only thing I'm not sure about is if the subdirectory "cache/" is necessary or if "omnisharp/" would have been enough. There is no other variable to theme.

Considering how recently this one was added and how large the package is, it is conceivable that more path variables will be added. So it seems safest to do what you have done.

**Pull request merged**
