### PR TITLE
psession: theme psession-elisp-objects-default-directory

### PR DESCRIPTION
**Pull request by manuel-uberti**
This PR adds support for [psession](https://github.com/thierryvolpiatto/psession).

If anything needs to be changed, feel free to ask and I'll update the PR accordingly.

### CODE REVIEW

**Comment by tarsius** [comment]
Please open a pr against the package itself to create the directory if necessary.

**Comment by manuel-uberti** [comment]
The package already creates the `elisp-objects` directory in `.emacs.d`. Are you referring to the `psession` one?

**Comment by manuel-uberti** [comment]
Following the discussion [here](https://github.com/thierryvolpiatto/psession/issues/12), does it make more sense now?

**Comment by manuel-uberti** [comment]
Thank you! :+1:

**Pull request merged**
