### PR TITLE
backup-directory-alist: Don't backup potentially sensitive data

### LINKED ISSUE #200: Unencrypted `password-store` entries are backed up
As noted [here](https://lonely.town/@wasamasa/110227701055899570), `pass` entries are backed up in plain text when `backup-directory-alist` is set to `nil`.

### PR DESCRIPTION
**Pull request by josephmturner**
Resolves #200

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks! I didn't see that before pushing my own fix. I've chosen to not set the variable at all, since other $EDITOR users might open files elsewhere.

**Comment by josephmturner** [comment]
Thank you!

**Comment by josephmturner** [comment]
For future reference, you can keep more-or-less the previous behavior by ignoring `/dev/shm/` and `/tmp/` but backing everything else up in a single backup dir.
```
(setq backup-directory-alist (list
                              ;; Don't backup potentially sensitive information (pass stores plaintext in /dev/shm/ and /tmp/)
                              (cons "^/dev/shm/" nil)
                              (cons "^/tmp/"     nil)
                              (cons "."         (expand-file-name (locate-user-emacs-file "var/backup/")))))

```

**Comment by tarsius** [comment]
I assume `pass` deletes the file it asked `$EDITOR` to edit, when done. But it does not know about the backup files, so those will persist until a reboot. So this is still not as safe as disabling backups altogether with `(setq make-backup-files nil)`.

You could also use custom `backup-enable-predicate` function that returns nil for `/dev/shm`. The default does so for `/tmp`, but not this directory.

**Pull request closed without merging**
