### PR TITLE
devdocs-browser: theme devdocs-browser-cache-directory

### PR DESCRIPTION
**Pull request by condy0919**
- This is a directory.
- Third party library https://github.com/blahgeek/emacs-devdocs-browser/

### CODE REVIEW

**Comment by tarsius** [comment]
Merged, but then I also added a6c8e0575766eb573a7add103836d578bd205962.

I would just have pushed this to this branch before merging, but...

**Comment by tarsius** [comment]
Unfortunately this pull-request asks for your `master` branch to be merged into ours.  It is better to use a dedicated feature branch instead, as [explained here](https://github.com/magit/magit/wiki/Dedicated-pull-request-branches).  It is too late for this pull-request now, but the next time you open a pull-request (in any repository really), then please use a feature branch.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by condy0919** [comment]
Sorry for that

**Comment by tarsius** [comment]
Np

**Pull request merged**
